# Generated by Django 5.2.7 on 2026-10-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_foto_portada'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Creó'), ('editar', 'Editó'), ('ver', 'Consultó'), ('verificar', 'Verificó'), ('desverificar', 'Quitó verificación')], max_length=20, verbose_name='Acción')),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Id del objeto')),
                ('cambios', models.JSONField(blank=True, default=dict, verbose_name='Cambios')),
                ('clinico', models.BooleanField(default=False, verbose_name='Dato clínico')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Modelo')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='accounts.paciente', verbose_name='Paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['paciente', '-created_at'], name='auditoria_a_pacient_0cbe30_idx'), models.Index(fields=['content_type', 'objeto_id'], name='auditoria_a_content_01a9c4_idx'), models.Index(fields=['accion', '-created_at'], name='auditoria_a_accion_2df1c7_idx')],
            },
        ),
    ]
