# Generated by Django 5.2.8 on 2025-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('alergias', models.BooleanField(default=False)),
                ('embarazo', models.BooleanField(default=False)),
                ('ninguna', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True, null=True)),
                ('dental_history', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
