# Generated by Django 5.2.8 on 2025-12-10 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=30, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('eps', models.CharField(blank=True, max_length=100, null=True)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('cardiopatia', models.BooleanField(default=False)),
                ('alergias', models.BooleanField(default=False)),
                ('embarazo', models.BooleanField(default=False)),
                ('ninguna', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True, null=True)),
                ('dental_history', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], max_length=3, verbose_name='Tipo de Identificación')),
                ('id_number', models.CharField(max_length=30, unique=True, verbose_name='Número de Identificación')),
                ('especialidad', models.CharField(choices=[('odontologia-general', 'Odontología General'), ('ortodoncia', 'Ortodoncia'), ('endodoncia', 'Endodoncia'), ('periodoncia', 'Periodoncia'), ('odontopediatria', 'Odontopediatría'), ('cirugia-oral', 'Cirugía Oral'), ('implantologia', 'Implantología'), ('estetica-dental', 'Estética Dental'), ('prostodoncia', 'Prostodoncia')], max_length=50, verbose_name='Especialidad')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('codigo_pais', models.CharField(default='+57', max_length=5, verbose_name='Código de país')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='Perfil verificado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['-created_at'],
            },
        ),
    ]
