# Generated by Django 5.2.8 on 2025-12-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=255, verbose_name='Nombre de la clínica/centro')),
                ('specialists_range', models.CharField(choices=[('1-5', '1-5 especialistas'), ('6-10', '6-10 especialistas'), ('11-20', '11-20 especialistas'), ('21-50', '21-50 especialistas'), ('51+', 'Más de 50 especialistas')], max_length=10, verbose_name='Rango de especialistas')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Centro Médico',
                'verbose_name_plural': 'Centros Médicos',
                'ordering': ['-created_at'],
            },
        ),
    ]
