# Generated by Django 5.2.7 on 2026-09-29 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_paciente_email_remove_paciente_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.BooleanField(default=False, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cardiopatia',
            field=models.BooleanField(default=False, verbose_name='Cardiopatía'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dental_history',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes odontológicos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='department',
            field=models.CharField(max_length=50, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='embarazo',
            field=models.BooleanField(default=False, verbose_name='Embarazo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de emergencia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gender',
            field=models.CharField(max_length=20, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hipertension',
            field=models.BooleanField(default=False, verbose_name='Hipertensión'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_type',
            field=models.CharField(max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medications',
            field=models.TextField(blank=True, null=True, verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ninguna',
            field=models.BooleanField(default=False, verbose_name='Ninguna condición'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
