# Generated by Django 5.2.7 on 2026-09-29 16:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.ruta_foto, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.ruta_portada, verbose_name='Foto de portada'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.ruta_foto, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.ruta_portada, verbose_name='Foto de portada'),
        ),
    ]
