# Generated by Django 5.2.7 on 2026-09-29 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
        ('citas', '0002_cita_consultorio_cita_duracion_minutos_and_more'),
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('concepto', models.CharField(max_length=180, verbose_name='Concepto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='emitida', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='citas.cita', verbose_name='Cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='accounts.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='accounts.profesional', verbose_name='Profesional')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='clinica.sede', verbose_name='Sede')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='clinica.tratamiento', verbose_name='Tratamiento')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('pse', 'PSE')], max_length=20, verbose_name='Método')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.factura', verbose_name='Factura')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['paciente', 'estado'], name='factura_paciente_estado'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='factura_valor_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['factura', 'created_at'], name='pago_factura_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pago_valor_positivo'),
        ),
    ]
