# Generated by Django 5.2.7 on 2026-09-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
        ('citas', '0002_cita_consultorio_cita_duracion_minutos_and_more'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes', models.TextField(blank=True, verbose_name='Antecedentes odontológicos')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('origen_migracion', models.BooleanField(default=False, help_text='Marca las historias copiadas desde el registro del paciente. No indica un dato clínico nuevo.', verbose_name='Creada al migrar datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de apertura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='accounts.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia clínica',
                'verbose_name_plural': 'Historias clínicas',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='citas.cita', verbose_name='Cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='accounts.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='accounts.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=150, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=80, verbose_name='Dosis')),
                ('frecuencia', models.CharField(max_length=80, verbose_name='Frecuencia')),
                ('duracion', models.CharField(max_length=80, verbose_name='Duración')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='historia.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Medicamento de la receta',
                'verbose_name_plural': 'Medicamentos de la receta',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota de evolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='citas.cita', verbose_name='Cita')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='accounts.profesional', verbose_name='Profesional')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='clinica.tratamiento', verbose_name='Tratamiento')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='historia.historiaclinica', verbose_name='Historia clínica')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['historia', 'created_at'], name='evolucion_historia_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fdi', models.PositiveSmallIntegerField(verbose_name='Diente (FDI)')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturacion', 'Obturación'), ('ausente', 'Ausente'), ('corona', 'Corona'), ('endodoncia', 'Endodoncia'), ('implante', 'Implante'), ('fractura', 'Fractura')], default='sano', max_length=20, verbose_name='Estado')),
                ('nota', models.CharField(blank=True, max_length=180, verbose_name='Nota')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dientes_actualizados', to='accounts.profesional', verbose_name='Actualizado por')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dientes', to='historia.historiaclinica', verbose_name='Historia clínica')),
            ],
            options={
                'verbose_name': 'Diente del odontograma',
                'verbose_name_plural': 'Dientes del odontograma',
                'ordering': ['codigo_fdi'],
                'indexes': [models.Index(fields=['historia', 'estado'], name='odontograma_historia_estado')],
                'constraints': [models.UniqueConstraint(fields=('historia', 'codigo_fdi'), name='odontograma_diente_unico')],
            },
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['paciente', 'created_at'], name='receta_paciente_fecha'),
        ),
    ]
