# Generated by Django 5.2.7 on 2026-09-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
        ('citas', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.consultorio', verbose_name='Consultorio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='clinica.tratamiento', verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida'), ('no_asistio', 'No asistió')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='accounts.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='accounts.profesional', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'fecha_hora'], name='cita_prof_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha_hora'], name='cita_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['consultorio', 'fecha_hora'], name='cita_consultorio_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha_hora'], name='cita_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('duracion_minutos__gte', 15), ('duracion_minutos__lte', 480)), name='cita_duracion_valida'),
        ),
    ]
