# Generated by Django 5.2.7 on 2026-09-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=80, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('horario_atencion', models.CharField(blank=True, max_length=180, verbose_name='Horario de atención')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['ciudad', 'nombre'],
                'indexes': [models.Index(fields=['ciudad', 'activa'], name='sede_ciudad_activa')],
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('piso', models.CharField(blank=True, max_length=20, verbose_name='Piso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorios', to='clinica.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('fin', models.DateTimeField(verbose_name='Fin')),
                ('motivo', models.CharField(max_length=180, verbose_name='Motivo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='accounts.profesional', verbose_name='Profesional')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos', to='clinica.consultorio', verbose_name='Consultorio')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='clinica.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Bloqueo de horario',
                'verbose_name_plural': 'Bloqueos de horario',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False, verbose_name='Sede principal')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_asignadas', to='accounts.profesional', verbose_name='Profesional')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_asignados', to='clinica.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Asignación de sede',
                'verbose_name_plural': 'Asignaciones de sede',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=30, verbose_name='Duración (minutos)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio de referencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='clinica.especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales_asignados', to='clinica.especialidad', verbose_name='Especialidad')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_asignadas', to='accounts.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Especialidad del profesional',
                'verbose_name_plural': 'Especialidades de profesionales',
                'constraints': [models.UniqueConstraint(fields=('profesional', 'especialidad'), name='profesional_especialidad_unica')],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades', to='clinica.consultorio', verbose_name='Consultorio')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='accounts.profesional', verbose_name='Profesional')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='clinica.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['profesional', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['profesional', 'dia_semana', 'activa'], name='disp_prof_dia_activa')],
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='disponibilidad_hora_fin_posterior')],
            },
        ),
        migrations.AddConstraint(
            model_name='consultorio',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='consultorio_unico_por_sede'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['profesional', 'inicio'], name='bloqueo_prof_inicio'),
        ),
        migrations.AddConstraint(
            model_name='bloqueohorario',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='bloqueo_fin_posterior'),
        ),
        migrations.AddConstraint(
            model_name='asignacionsede',
            constraint=models.UniqueConstraint(fields=('profesional', 'sede'), name='asignacion_sede_unica'),
        ),
        migrations.AddIndex(
            model_name='tratamiento',
            index=models.Index(fields=['activo', 'nombre'], name='tratamiento_activo_nombre'),
        ),
    ]
