# Generated by Django 5.2.7 on 2026-09-29 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paciente_options_alter_paciente_address_and_more'),
        ('comunicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='accounts.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='accounts.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000, verbose_name='Texto')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='comunicacion.conversacion', verbose_name='Conversación')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500, verbose_name='Texto')),
                ('imagen', models.ImageField(blank=True, upload_to='publicaciones/%Y/%m/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='accounts.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta', to='accounts.paciente', verbose_name='Paciente')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_gusta', to='comunicacion.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=280, verbose_name='Texto')),
                ('estado', models.CharField(choices=[('pendiente', 'En revisión'), ('publicado', 'Publicado'), ('oculto', 'Oculto')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='accounts.paciente', verbose_name='Paciente')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='comunicacion.publicacion', verbose_name='Publicación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='accounts.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='accounts.profesional', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['paciente', 'created_at'], name='conversacion_paciente'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['profesional', 'created_at'], name='conversacion_profesional'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('paciente', 'profesional'), name='conversacion_unica'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'created_at'], name='mensaje_conversacion_fecha'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'leido'], name='mensaje_conversacion_leido'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['profesional', 'created_at'], name='publicacion_prof_fecha'),
        ),
        migrations.AddConstraint(
            model_name='megusta',
            constraint=models.UniqueConstraint(fields=('publicacion', 'paciente'), name='me_gusta_unico'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['publicacion', 'estado'], name='comentario_publicacion_estado'),
        ),
        migrations.AddConstraint(
            model_name='seguimiento',
            constraint=models.UniqueConstraint(fields=('paciente', 'profesional'), name='seguimiento_unico'),
        ),
    ]
